%% Intersubject normalisation of features - Z-score by controls
% Z score patient measures by controls Directory of patients
clear all; close all;

current_dir = pwd;
addpath(current_dir)

%Change to appropriate subject dir
SUBJECTS_DIR = 'path\to\subjects';
cd(SUBJECTS_DIR)
setenv SUBJECTS_DIR .
addpath('path\to\FreeSurfer matlab dir')

%change to appropriate prefix for all subjects
Subs = dir(fullfile(SUBJECTS_DIR, 'P*'));
Subs = {Subs.name};

Subs_HC = dir(fullfile(SUBJECTS_DIR, 'V*'));
Cons = {Subs_HC.name};

% Load cortex label. +1 for freesurfer matlab indexing
Cortex = read_label('fsaverage_sym', 'lh.cortex');
Cortex = Cortex(:, 1) + 1;
 
Measures={...
    '.thickness_z_on_lh.sm10.mgh'; '.lh-rh.thickness_z.sm10.mgh';...
    '.w-g.pct_z_on_lh.sm10.mgh';'.lh-rh.w-g.pct_z.sm10.mgh';...
    '.pial.K_filtered_2_z_on_lh.sm20.mgh';'.lh-rh.pial.K_filtered_2_z.sm20.mgh';...
    '.curv_on_lh.mgh';'.sulc_on_lh.mgh';...
    ...
    '.thickness_z_on_lh.mgh'; '.lh-rh.thickness_z.mgh';...
    '.w-g.pct_z_on_lh.mgh';'.lh-rh.w-g.pct_z.mgh';...
    '.pial.K_filtered_2_z_on_lh.mgh';'.lh-rh.pial.K_filtered_2_z.mgh';...
    ...
    '.gm_MRF_T1_0.75_z_on_lh.sm10.mgh';'.gm_MRF_T1_0.5_z_on_lh.sm10.mgh';...
    '.gm_MRF_T1_0.25_z_on_lh.sm10.mgh';'.gm_MRF_T1_0_z_on_lh.sm10.mgh';...
    '.wm_MRF_T1_0.5_z_on_lh.sm10.mgh';'.wm_MRF_T1_1_z_on_lh.sm10.mgh';...
    '.lh-rh.gm_MRF_T1_0.75_z.sm10.mgh';'.lh-rh.gm_MRF_T1_0.5_z.sm10.mgh';...
    '.lh-rh.gm_MRF_T1_0.25_z.sm10.mgh';'.lh-rh.gm_MRF_T1_0_z.sm10.mgh';...
    '.lh-rh.wm_MRF_T1_0.5_z.sm10.mgh';'.lh-rh.wm_MRF_T1_1_z.sm10.mgh';...
    ...
    '.gm_MRF_T1_0.75_z_on_lh.mgh';'.gm_MRF_T1_0.5_z_on_lh.mgh';...
    '.gm_MRF_T1_0.25_z_on_lh.mgh';'.gm_MRF_T1_0_z_on_lh.mgh';...
    '.wm_MRF_T1_0.5_z_on_lh.mgh';'.wm_MRF_T1_1_z_on_lh.mgh';...
    '.lh-rh.gm_MRF_T1_0.75_z.mgh';'.lh-rh.gm_MRF_T1_0.5_z.mgh';...
    '.lh-rh.gm_MRF_T1_0.25_z.mgh';'.lh-rh.gm_MRF_T1_0_z.mgh';...
    '.lh-rh.wm_MRF_T1_0.5_z.mgh';'.lh-rh.wm_MRF_T1_1_z.mgh';...
    ...
    '.gm_MRF_T2_tr_0.75_z_on_lh.sm10.mgh';'.gm_MRF_T2_tr_0.5_z_on_lh.sm10.mgh';...
    '.gm_MRF_T2_tr_0.25_z_on_lh.sm10.mgh';'.gm_MRF_T2_tr_0_z_on_lh.sm10.mgh';...
    '.wm_MRF_T2_tr_0.5_z_on_lh.sm10.mgh';'.wm_MRF_T2_tr_1_z_on_lh.sm10.mgh';...
    '.lh-rh.gm_MRF_T2_tr_0.75_z.sm10.mgh';'.lh-rh.gm_MRF_T2_tr_0.5_z.sm10.mgh';...
    '.lh-rh.gm_MRF_T2_tr_0.25_z.sm10.mgh';'.lh-rh.gm_MRF_T2_tr_0_z.sm10.mgh';...
    '.lh-rh.wm_MRF_T2_tr_0.5_z.sm10.mgh';'.lh-rh.wm_MRF_T2_tr_1_z.sm10.mgh';...
    ...
    '.gm_MRF_T2_tr_0.75_z_on_lh.mgh';'.gm_MRF_T2_tr_0.5_z_on_lh.mgh';...
    '.gm_MRF_T2_tr_0.25_z_on_lh.mgh';'.gm_MRF_T2_tr_0_z_on_lh.mgh';...
    '.wm_MRF_T2_tr_0.5_z_on_lh.mgh';'.wm_MRF_T2_tr_1_z_on_lh.mgh';...
    '.lh-rh.gm_MRF_T2_tr_0.75_z.mgh';'.lh-rh.gm_MRF_T2_tr_0.5_z.mgh';...
    '.lh-rh.gm_MRF_T2_tr_0.25_z.mgh';'.lh-rh.gm_MRF_T2_tr_0_z.mgh';...
    '.lh-rh.wm_MRF_T2_tr_0.5_z.mgh';'.lh-rh.wm_MRF_T2_tr_1_z.mgh';...
    ...
    '.gm_FLAIR_0.75_z_on_lh.sm10.mgh';'.gm_FLAIR_0.5_z_on_lh.sm10.mgh';...
    '.gm_FLAIR_0.25_z_on_lh.sm10.mgh';'.gm_FLAIR_0_z_on_lh.sm10.mgh';...
    '.wm_FLAIR_0.5_z_on_lh.sm10.mgh';'.wm_FLAIR_1_z_on_lh.sm10.mgh';...
    '.lh-rh.gm_FLAIR_0.75_z.sm10.mgh';'.lh-rh.gm_FLAIR_0.5_z.sm10.mgh';...
    '.lh-rh.gm_FLAIR_0.25_z.sm10.mgh';'.lh-rh.gm_FLAIR_0_z.sm10.mgh';...
    '.lh-rh.wm_FLAIR_0.5_z.sm10.mgh';'.lh-rh.wm_FLAIR_1_z.sm10.mgh';...
    ...
    '.gm_FLAIR_0.75_z_on_lh.mgh';'.gm_FLAIR_0.5_z_on_lh.mgh';...
    '.gm_FLAIR_0.25_z_on_lh.mgh';'.gm_FLAIR_0_z_on_lh.mgh';...
    '.wm_FLAIR_0.5_z_on_lh.mgh';'.wm_FLAIR_1_z_on_lh.mgh';...
    '.lh-rh.gm_FLAIR_0.75_z.mgh';'.lh-rh.gm_FLAIR_0.5_z.mgh';...
    '.lh-rh.gm_FLAIR_0.25_z.mgh';'.lh-rh.gm_FLAIR_0_z.mgh';...
    '.lh-rh.wm_FLAIR_0.5_z.mgh';'.lh-rh.wm_FLAIR_1_z.mgh';...
    };

for order = 1:length(Subs)
    
    s = Subs{order}; 
    display(s);
    
    % For each measure normalise by controls    
    for L = 1:length(Measures)

        Normal_C_L = zeros(length(Cons), length(Cortex));
        Normal_C_R = zeros(length(Cons), length(Cortex)); 

        for c = 1:length(Cons)
            con = Cons{c};

            % Load measure in controls and extract cortical values
            ML_C = MRIread(fullfile(con, 'xhemi', 'surf', ['lh' Measures{L}]));
            Normal_C_L(c, :) = ML_C.vol(Cortex);
            clear ML_C

            MR_C = MRIread(fullfile(con, 'xhemi', 'surf', ['rh' Measures{L}]));
            Normal_C_R(c, :) = MR_C.vol(Cortex);

            clear con ML_C
        end

        Measure_L = zeros(1, length(Cortex));
        Measure_R = zeros(1, length(Cortex));

        %Load patient data measure for each hemisphere
        ML = MRIread(fullfile(s, 'xhemi', 'surf', ['lh' Measures{L}]));
        Measure_L(:) = ML.vol(Cortex);

        MR = MRIread(fullfile(s, 'xhemi', 'surf', ['rh' Measures{L}]));
        Measure_R(:) = MR.vol(Cortex);

        % Normalise left hemi by controls by mean and std
        zMeasure_L = zeros(size(Measure_L));
        meanY = mean(Normal_C_L, 1, "omitnan");
        stdY = std(Normal_C_L, 0, 1, "omitnan");

        for i = 1 : size(Measure_L,1)
            zMeasure_L(i, :) = (Measure_L(i, :) - meanY)./stdY;
        end
        clear meanY stdY

        % Normalise right hemi by controls
        zMeasure_R = zeros(size(Measure_R));
        meanY = mean(Normal_C_R, 1, "omitnan");
        stdY = std(Normal_C_R, 0, 1, "omitnan");

        for i = 1 : size(Measure_R,1)
            zMeasure_R(i, :) = (Measure_R(i, :) - meanY)./stdY;
        end
        clear meanY stdY

        Dummy = MRIread(fullfile(s, 'xhemi', 'surf', 'lh.thickness_z_on_lh.sm10.mgh'));
        Dummy.vol(:) = 0;

        Dummy.vol(Cortex) = zMeasure_L(:);
        MRIwrite(Dummy, fullfile(s, 'xhemi', 'surf', ['lh.Z_by_controls' Measures{L}]));

        Dummy.vol(Cortex) = zMeasure_R(:);
        MRIwrite(Dummy, fullfile(s, 'xhemi', 'surf', ['rh.Z_by_controls' Measures{L}]));

        clear Normal_C_L Normal_C_R
        clear Measure_L Measure_R ML MR zMeasure_L zMeasure_R Dummy Normal_C_L Normal_C_R
    end 

    clear s
end

cd(current_dir)