clear all; close all;

% Change to appropriate subject dir
SUBJECTS_DIR = 'path\to\subjects';
cd(SUBJECTS_DIR)
setenv SUBJECTS_DIR .
addpath('path\to\FreeSurfer matlab dir')

% Change to appropriate prefix for all subjects
Subs_P = dir(fullfile(SUBJECTS_DIR, 'P*'));
Subs_HC = dir(fullfile(SUBJECTS_DIR, 'V*'));
Subs = [Subs_P; Subs_HC];
Subs = {Subs.name};

% List of features to be normalised

Measures={...
    % Smoothed SBM features
    '.thickness.sm10.mgh'; ...
    '.w-g.pct.sm10.mgh'; ...
    '.pial.K_filtered_2.sm20.mgh'; ...
    % Smoothed FLAIR projection features
    '.gm_FLAIR_0.sm10.mgh'; ...
    '.gm_FLAIR_0.25.sm10.mgh'; ...
    '.gm_FLAIR_0.5.sm10.mgh'; ...
    '.gm_FLAIR_0.75.sm10.mgh'; ...
    '.wm_FLAIR_0.5.sm10.mgh'; ...
    '.wm_FLAIR_1.sm10.mgh'; ...
    % Smoothed MRF T1 projection features
    '.gm_MRF_T1_0.sm10.mgh'; ...
    '.gm_MRF_T1_0.25.sm10.mgh'; ...
    '.gm_MRF_T1_0.5.sm10.mgh'; ...
    '.gm_MRF_T1_0.75.sm10.mgh'; ...
    '.wm_MRF_T1_0.5.sm10.mgh'; ...
    '.wm_MRF_T1_1.sm10.mgh'; ...
    % Smoothed MRF T2 projection features
    '.gm_MRF_T2_tr_0.sm10.mgh'; ...
    '.gm_MRF_T2_tr_0.25.sm10.mgh'; ...
    '.gm_MRF_T2_tr_0.5.sm10.mgh'; ...
    '.gm_MRF_T2_tr_0.75.sm10.mgh'; ...
    '.wm_MRF_T2_tr_0.5.sm10.mgh'; ...
    '.wm_MRF_T2_tr_1.sm10.mgh'; ...
    % SBM features
    '.thickness.mgh'; ...
    '.w-g.pct.mgh'; ...
    '.pial.K_filtered_2.mgh'; ...
    % FLAIR projection features
    '.gm_FLAIR_0.mgh'; ...
    '.gm_FLAIR_0.25.mgh'; ...
    '.gm_FLAIR_0.5.mgh'; ...
    '.gm_FLAIR_0.75.mgh'; ...
    '.wm_FLAIR_0.5.mgh';...
    '.wm_FLAIR_1.mgh'; ...
    % T1 projection features
    '.gm_MRF_T1_0.mgh'; ...
    '.gm_MRF_T1_0.25.mgh'; ...
    '.gm_MRF_T1_0.5.mgh'; ...
    '.gm_MRF_T1_0.75.mgh'; ...
    '.wm_MRF_T1_0.5.mgh'; ...
    '.wm_MRF_T1_1.mgh'; ...
    % T2 projection features
    '.gm_MRF_T2_tr_0.mgh'; ...
    '.gm_MRF_T2_tr_0.25.mgh'; ...
    '.gm_MRF_T2_tr_0.5.mgh'; ...
    '.gm_MRF_T2_tr_0.75.mgh'; ...
    '.wm_MRF_T2_tr_0.5.mgh'; ...
    '.wm_MRF_T2_tr_1.mgh'; ...
   };

Measures2={'.pial.K_filtered_2.mgh', '.pial.K_filtered_2.sm20.mgh'};

for order = 1:length(Subs)
    
    s = Subs{order};
    
    % Load cortex label for each hemisphere
    Cortexlh = read_label(['', s, ''], 'lh.cortex');
    
    % Add 1 because freesurfer indexes from 0, and matlab from 1.
    Cortexlh = Cortexlh(:, 1) + 1;
    Cortexrh = read_label(['', s, ''], 'rh.cortex');
    Cortexrh = Cortexrh(:, 1) + 1;
 
    % Load in overlay files for all measures
    for L = 1:length(Measures)
        M_lh = MRIread(['', s, '/surf/lh', Measures{L}, '']);
        M_rh = MRIread(['', s, '/surf/rh', Measures{L}, '']); 

        % Normalise by mean and std
        M = [M_lh.vol(Cortexlh), M_rh.vol(Cortexrh)];
        meanM = mean(M);
        stdM = std(M);
        M_lh.vol(1, :) = (M_lh.vol(1, :) - meanM)./stdM;
        M_rh.vol(1, :) = (M_rh.vol(1, :) - meanM)./stdM;

        % Create string for saving output after removing last 9 characters.
        if strcmp(Measures{L}(end-7:end-4), 'sm10')
            Meas_output = Measures{L}(1:end-9);

            MRIwrite(M_lh, ['', s, '/surf/lh', Meas_output, '_z.sm10.mgh']);
            MRIwrite(M_rh, ['', s, '/surf/rh', Meas_output, '_z.sm10.mgh']);
        else
            Meas_output = Measures{L}(1:end-4);

            MRIwrite(M_lh, ['', s, '/surf/lh', Meas_output, '_z.mgh']);
            MRIwrite(M_rh, ['', s, '/surf/rh', Meas_output, '_z.mgh']);
        end
    end
    
    for L = 1:length(Measures2)

        M_lh = MRIread(['', s, '/surf/lh', Measures2{L}, '']);
        M_rh = MRIread(['', s, '/surf/rh', Measures2{L}, '']); 
   
        % Normalise by mean and std
        M = [M_lh.vol(Cortexlh), M_rh.vol(Cortexrh)];
        meanM = mean(M);
        stdM = std(M);
        M_lh.vol(1, :) = (M_lh.vol(1, :) - meanM)./stdM;
        M_rh.vol(1, :) = (M_rh.vol(1, :) - meanM)./stdM;
    
        % Create string for saving output after removing last 9 characters.
        if strcmp(Measures2{L}(end-7:end-4), 'sm20')
            Meas_output = Measures2{L}(1:end-9);
            MRIwrite(M_lh, ['', s, '/surf/lh', Meas_output, '_z.sm20.mgh']);
            MRIwrite(M_rh, ['', s, '/surf/rh', Meas_output, '_z.sm20.mgh']);
        else
            Meas_output = Measures2{L}(1:end-4);
            MRIwrite(M_lh, ['', s, '/surf/lh', Meas_output, '_z.mgh']);
            MRIwrite(M_rh, ['', s, '/surf/rh', Meas_output, '_z.mgh']);
        end
    end
end

cd(current_dir)
